# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: update csv

on:
  schedule:
    - cron: '10 19 * * *'
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - 
      name: Install Chrome
      run: |
        sudo wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo apt update
        sudo apt-get install google-chrome-stable
    - 
      name: Install Package
      run: |
        pip install chromedriver-binary==94.*
        pip install selenium
    - name: Install dependencies
      run: |
        pip install get-chrome-driver --upgrade
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run update_csv
      run: python update_csv.py
    - name: Commit changes
      run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add -u
          git add temp/*.png
          git diff-index --quiet HEAD || git commit -m "Update CSV file"
          git push
